Lesson 3
dimasumskoy/qna pull request #1
Opened 2017-07-04 23:39 UTC by dimasumskoy

Добавил тесты для полей в таблицах и ассоциаций. Вроде пока больше нечего тестировать.

2017-07-05 05:38 UTC, iBublik requested changes

2017-07-05 05:38 UTC, iBublik commented on app/models/answer.rb
> +  belongs_to :question, foreign_key: :question_id
Зачем явно задавать имя внешнего ключа? У тебя ассоциации названы по конвенциям, так что рельса сама построит связи.

2017-07-05 05:38 UTC, iBublik commented on app/models/question.rb
> +  has_many :answers, foreign_key: :question_id
Тут тоже foreign_key лишний.
И что будет с ответами при удалении вопроса? Нужно это обработать и протестить (в shoulda-matchers есть нужная опция)

2017-07-05 05:38 UTC, iBublik commented on spec/models/answer_spec.rb
> +  it { should belong_to(:question).with_foreign_key(:question_id) }
В моделях мы пишем сначала ассоциации, потом валидации - придерживайся в тестах того же порядка. И отделяй эти блоки пустыми строками, так проще читается

2017-07-05 05:38 UTC, iBublik commented on db/migrate/20170704225236_create_answers.rb
> +      t.belongs_to :question, foreign_key: true, index: true
Указание `index: true` избыточно, т.к. в 5 рельсе для связей индексы создаются по умолчанию

2017-07-05 05:38 UTC, iBublik commented on spec/factories/answers.rb
> +
Грустно, что фабрики пустые. Ну пока это не критично, но в следующем занятии их надо будет заполнить :)

2017-07-05 10:01 UTC, dimasumskoy commented on app/models/answer.rb
> +  belongs_to :question, foreign_key: :question_id
А разве в этой связи не нужно добавлять ограничение на внешний ключ для ссылочной целостности?

2017-07-05 10:06 UTC, dimasumskoy commented on db/migrate/20170704225236_create_answers.rb
> +      t.belongs_to :question, foreign_key: true, index: true
Я думал, индексы по умолчанию создаются через `add_reference` и им подобных, а `belongs_to` все еще требует его указания. Но окей, запомню

2017-07-05 19:49 UTC, iBublik commented on app/models/answer.rb
> +  belongs_to :question, foreign_key: :question_id
Этот контроль осуществляет СУБД (при указании опции `foreign_key: true` или вызове метода `add_foreign_key` в миграциях), а не Rails. В модели опция `foreign_key` служит для указания имени поля, по которому будут связываться модели.
```ruby
class User < ApplicationRecord
  # указываем имя внешнего ключа, т.к. иначе бы искалось бы поле `user_id`
  has_many :post, foreign_key: :author_id
end

class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
end
```

2017-07-06 06:28 UTC, vkurennov approved these changes

2017-07-07 18:02 UTC, merged