Lesson 4
dimasumskoy/qna pull request #2
Opened 2017-07-09 02:14 UTC by dimasumskoy

Не уверен, нужен ли пока экшн index для обоих контроллеров, но на всякий случай реализовал его и тесты к нему.
Так же пока непонятно, при создании ответа редиректить на сам ответ (т.е просто на show), или же на вопрос, к которому создавался ответ. В общем, решил пока не забегать вперед и сделал по-простому.

2017-07-09 12:53 UTC, vkurennov requested changes

2017-07-09 12:53 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { valid_answer_attributes }.to change(Answer, :count).by(1)
Тут надо проверить, что ответ связывается с вопросом, это можно сделать прямо в change через ассоциации вопроса

2017-07-10 06:20 UTC, iBublik commented on app/models/answer.rb
> +  validates :body, :question_id, presence: true
Rails 5 автоматом валидирует связи (чтоб отключить нужно в belongs_to добавить опцию `optional: true`), так что эта проверка избыточна

2017-07-10 06:20 UTC, iBublik commented on spec/models/answer_spec.rb
> +  it { should validate_presence_of :question_id }
Это лишнее

2017-07-10 06:20 UTC, iBublik commented on spec/factories/answers.rb
> +  factory :invalid_answer, class: 'Answer' do
Фабрики можно вкладывать друг в друга - это некое подобие наследования. Тогда не придется писать класс объекта, который создает фабрика
```ruby
factory :answer do
  body 'answer body'
  
  factory :invalid_answer do
    ...
  end
end

2017-07-10 06:20 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answers = Answer.all
В качестве тренировки - ок, но сам подумай - зачем нам список всех ответов вне контекста вопроса? :) Я понимаю если бы возвращались ответы вопроса, id которого в роутах передается :) 
А вообще можешь не заморачиваться - дальше мы будем выводить ответ на вопрос на страничке самого вопроса, так что этот экшн надо будет убрать

2017-07-10 06:49 UTC, vkurennov approved these changes

2017-07-11 01:41 UTC, merged